/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package controle;

import conexao.Conexao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author dti
 */
public class Frm_Disciplinas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_Disciplinas
     */
    Conexao con_disciplina;
    public Frm_Disciplinas() {
        initComponents(); 
       con_disciplina = new Conexao(); // inicialização do objeto
        con_disciplina.conecta(); // chama o método que conecta
        con_disciplina.executaSQL("select * from tbldisciplinas order by CodDisc");
        preencherTabela();
        posicionarRegistro();
        tblDisciplinas.setAutoCreateRowSorter(true);
    }
public void preencherTabela(){
          tblDisciplinas.getColumnModel().getColumn(0).setPreferredWidth(4);
          tblDisciplinas.getColumnModel().getColumn(1).setPreferredWidth(50);
          tblDisciplinas.getColumnModel().getColumn(2).setPreferredWidth(50);
          tblDisciplinas.getColumnModel().getColumn(3).setPreferredWidth(120);
          
         
        
        DefaultTableModel modelo = (DefaultTableModel) tblDisciplinas.getModel();
        modelo.setNumRows(0);
        
        try {
           con_disciplina.resultset.beforeFirst();
            while(con_disciplina.resultset.next()){
                modelo.addRow(new Object[]{
                   con_disciplina.resultset.getString("CodDisc"), con_disciplina.resultset.getString("CodCurso"), con_disciplina.resultset.getString("NomeDisc"), con_disciplina.resultset.getString("Descricaodisc")

                });
            }
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null,"\n Erro ao listar dados da tabela!! :\n "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void posicionarRegistro(){
        try {
            con_disciplina.resultset.first();
            mostrar_Dados();
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null,"Não foi possível posicionar no primeiro registro:"+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    //método que irá mostrar os dados do registro selecionado nos campos de cadastro
    public void mostrar_Dados(){
        try {
           
            txt_CodDisc.setText(con_disciplina.resultset.getString("CodDisc"));
            txt_Codigo.setText(con_disciplina.resultset.getString("CodCurso"));
            txt_Nome.setText(con_disciplina.resultset.getString("NomeDisc"));
            txt_Descricao.setText(con_disciplina.resultset.getString("Descricaodisc"));
            
           
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null,"Não localizou dados: "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_Codigo = new javax.swing.JLabel();
        txt_Codigo = new javax.swing.JTextField();
        lbl_CodDisc = new javax.swing.JLabel();
        txt_CodDisc = new javax.swing.JTextField();
        lbl_Nome = new javax.swing.JLabel();
        txt_Nome = new javax.swing.JTextField();
        btn_Novo = new javax.swing.JButton();
        btn_PrimeiroRegistro = new javax.swing.JButton();
        btn_Gravar = new javax.swing.JButton();
        btn_Anterior = new javax.swing.JButton();
        btn_Alterar = new javax.swing.JButton();
        btn_Proximo = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_Ultimo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisciplinas = new javax.swing.JTable();
        lbl_Descricao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Descricao = new javax.swing.JTextArea();
        txt_pesquisa = new javax.swing.JTextField();
        lbl_pesquisarCliente = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Disciplinas");

        jPanel2.setBackground(new java.awt.Color(196, 219, 247));

        jLabel3.setBackground(new java.awt.Color(196, 219, 247));
        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 50, 98));
        jLabel3.setText("Disciplinas");

        lbl_Codigo.setFont(new java.awt.Font("Eras Demi ITC", 1, 15)); // NOI18N
        lbl_Codigo.setForeground(new java.awt.Color(2, 50, 98));
        lbl_Codigo.setText("Código Curso:");

        lbl_CodDisc.setFont(new java.awt.Font("Eras Demi ITC", 1, 15)); // NOI18N
        lbl_CodDisc.setForeground(new java.awt.Color(2, 50, 98));
        lbl_CodDisc.setText("Codigo Disciplinas:");

        lbl_Nome.setFont(new java.awt.Font("Eras Demi ITC", 1, 15)); // NOI18N
        lbl_Nome.setForeground(new java.awt.Color(2, 50, 98));
        lbl_Nome.setText("Nome:");

        btn_Novo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add.png"))); // NOI18N
        btn_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovoActionPerformed(evt);
            }
        });

        btn_PrimeiroRegistro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_PrimeiroRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/resultset_first.png"))); // NOI18N
        btn_PrimeiroRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrimeiroRegistroActionPerformed(evt);
            }
        });

        btn_Gravar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/disk.png"))); // NOI18N
        btn_Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GravarActionPerformed(evt);
            }
        });

        btn_Anterior.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/resultset_previous.png"))); // NOI18N
        btn_Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnteriorActionPerformed(evt);
            }
        });

        btn_Alterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/application_edit.png"))); // NOI18N
        btn_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AlterarActionPerformed(evt);
            }
        });

        btn_Proximo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Proximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/resultset_next.png"))); // NOI18N
        btn_Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProximoActionPerformed(evt);
            }
        });

        btn_excluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/application_delete.png"))); // NOI18N
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_Ultimo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/resultset_last.png"))); // NOI18N
        btn_Ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UltimoActionPerformed(evt);
            }
        });

        tblDisciplinas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblDisciplinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código Curso", "Código Disciplinas", "Nome", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisciplinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDisciplinasMouseClicked(evt);
            }
        });
        tblDisciplinas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblDisciplinasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblDisciplinas);

        lbl_Descricao.setFont(new java.awt.Font("Eras Demi ITC", 1, 15)); // NOI18N
        lbl_Descricao.setForeground(new java.awt.Color(2, 50, 98));
        lbl_Descricao.setText("Descrição:");

        txt_Descricao.setColumns(20);
        txt_Descricao.setRows(5);
        jScrollPane2.setViewportView(txt_Descricao);

        txt_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pesquisaActionPerformed(evt);
            }
        });
        txt_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pesquisaKeyReleased(evt);
            }
        });

        lbl_pesquisarCliente.setFont(new java.awt.Font("Eras Demi ITC", 0, 15)); // NOI18N
        lbl_pesquisarCliente.setForeground(new java.awt.Color(2, 50, 98));
        lbl_pesquisarCliente.setText("Pesquisar pelo do  nome do Curso:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lbl_pesquisarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(342, 342, 342))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_CodDisc)
                        .addGap(19, 19, 19)
                        .addComponent(txt_CodDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Codigo)
                                    .addComponent(lbl_Nome)
                                    .addComponent(lbl_Descricao))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txt_Nome)
                                    .addComponent(jScrollPane2)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_PrimeiroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Gravar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lbl_CodDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_CodDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nome)
                    .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Descricao)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Anterior)
                    .addComponent(btn_Proximo)
                    .addComponent(btn_Ultimo)
                    .addComponent(btn_PrimeiroRegistro)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_Novo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_Gravar, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_excluir)
                        .addComponent(btn_Alterar, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pesquisarCliente)
                    .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 967, 732);
    }// </editor-fold>//GEN-END:initComponents

    private void tblDisciplinasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDisciplinasKeyPressed
        int linha_selecionada = tblDisciplinas.getSelectedRow();
        
        txt_CodDisc.setText(tblDisciplinas.getValueAt(linha_selecionada, 0).toString());
        txt_Codigo.setText(tblDisciplinas.getValueAt(linha_selecionada,1).toString());
        txt_Nome.setText(tblDisciplinas.getValueAt(linha_selecionada, 2).toString());
        txt_Descricao.setText(tblDisciplinas.getValueAt(linha_selecionada, 3).toString());
        
        
    }//GEN-LAST:event_tblDisciplinasKeyPressed

    private void tblDisciplinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisciplinasMouseClicked
    int linha_selecionada = tblDisciplinas.getSelectedRow();
        
        txt_CodDisc.setText(tblDisciplinas.getValueAt(linha_selecionada, 0).toString());
        txt_Codigo.setText(tblDisciplinas.getValueAt(linha_selecionada,1).toString());
        txt_Nome.setText(tblDisciplinas.getValueAt(linha_selecionada, 2).toString());
        txt_Descricao.setText(tblDisciplinas.getValueAt(linha_selecionada, 3).toString());
    }//GEN-LAST:event_tblDisciplinasMouseClicked

    private void btn_UltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UltimoActionPerformed
try {
            con_disciplina.resultset.last();
            mostrar_Dados();
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no último registro: "+erro);
        }       
    }//GEN-LAST:event_btn_UltimoActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
String sql="";
        try{
            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro: ","Confirmar Exclusção",JOptionPane.YES_NO_OPTION,3);
                 if(resposta==0){
                     sql="delete from tbldisciplinas where CodDisc = "+txt_CodDisc.getText();
                        int excluir = con_disciplina.statement.executeUpdate(sql);
                        if(excluir==1){
                         JOptionPane.showMessageDialog(null,"Exclusão realizada com sucesso!!","Mensageem do Programa",JOptionPane.INFORMATION_MESSAGE);   
                         con_disciplina.executaSQL("select * from tbldisciplinas order by CodDisc");
                         con_disciplina.resultset.first();
                         preencherTabela();
                         posicionarRegistro();
                        }
                        else{
                            JOptionPane.showInternalMessageDialog(null," Operação cancelada pelo usuário!!","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
                        }
                }
        }
        catch(SQLException excecao){
            JOptionPane.showMessageDialog(null,"Erro na exclusão: "+excecao,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }         
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProximoActionPerformed
try { 
            //se o registro selecionado não for o último, ele irá passar para o próximo registro
            //senão, ele irá para o primeiro registro
            if( con_disciplina.resultset.isLast() == false){
                 con_disciplina.resultset.next();
                mostrar_Dados();
            }else{
                con_disciplina.resultset.first();
               mostrar_Dados(); 
            }
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no próximo registro: "+erro);
        }         
    }//GEN-LAST:event_btn_ProximoActionPerformed

    private void btn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlterarActionPerformed
       
        String CodDisc = txt_CodDisc.getText();
         String CodCurso= txt_Codigo.getText();
        String Nome = txt_Nome.getText(); 
        String Descricao =  txt_Descricao.getText();
       
        
        String sql;
        String msg="";
        
        try{
            if(txt_Codigo.getText().equals("0")){
                sql="insert into tbldisciplinas (CodDisc,CodCurso, NomeDisc, Descricaodisc) values ('" + CodDisc + "','" + CodCurso + "','" + Nome + "','" + Descricao + "')";
                msg="Gravação de um novo registro";
            }
            else{
                sql="update tbldisciplinas set NomeDisc='" + Nome + "', Descricaodisc='" + Descricao+"' where CodDisc= " + txt_CodDisc.getText();
                msg="Alteração de registro";
            }
           
            con_disciplina.statement.executeUpdate(sql);
                 JOptionPane.showMessageDialog(null, " Gravação realizada com sucesso!!!", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);

            con_disciplina.executaSQL("select * from tbldisciplinas order by CodDisc");
            preencherTabela();
        }
        
        catch (SQLException errosql){
            JOptionPane.showMessageDialog(null,"\n Erro na gravação:\n"+errosql,"Mensagem do programa",JOptionPane.INFORMATION_MESSAGE);
        }     
    }//GEN-LAST:event_btn_AlterarActionPerformed

    private void btn_AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnteriorActionPerformed
try {
            //atribuindo o numero do id que está em uso á variavel, funcionando como "linha selecionada"
            int id_selecionado =  con_disciplina.resultset.getInt(1);

            //se o Id selecionado for maior que 1, então ele irá selecionar o registro anterior, senão, irá para o primeiro
            if(id_selecionado > 1){
                con_disciplina.resultset.previous();
                mostrar_Dados();
            }else{
                con_disciplina.resultset.first();
                mostrar_Dados();
            }

        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no registro anterior: "+erro);
        }      
    }//GEN-LAST:event_btn_AnteriorActionPerformed

    private void btn_GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GravarActionPerformed
       String CodCurso= txt_Codigo.getText();
        String CodDisc = txt_CodDisc.getText();
        String Nome = txt_Nome.getText(); 
        String Descricao =  txt_Descricao.getText();
       
        
        try{
            String insert_sql="insert into tbldisciplinas (CodDisc,CodCurso , NomeDisc, Descricaodisc) values ('" + CodDisc + "','" + CodCurso + "','" + Nome + "','" + Descricao + "')";
            con_disciplina.statement.executeUpdate(insert_sql);
             JOptionPane.showMessageDialog(null, "Gravação realizada ", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
            
            con_disciplina.executaSQL("select * from tbldisciplinas order by CodDisc");
            preencherTabela();
            
           
        }
        
        catch(SQLException errosql){
            JOptionPane.showMessageDialog(null, "\n Erro na gravação: \n"+errosql,"Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
        }              
    }//GEN-LAST:event_btn_GravarActionPerformed

    private void btn_PrimeiroRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrimeiroRegistroActionPerformed
 try {
        con_disciplina.resultset.first();
        mostrar_Dados();
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o primeiro registro: "+erro);
        }    
    }//GEN-LAST:event_btn_PrimeiroRegistroActionPerformed

    private void btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoActionPerformed
        txt_Codigo.setText("");
        txt_CodDisc.setText("");
        txt_Nome.setText("");
        txt_Descricao.setText("");
       
        txt_Codigo.requestFocus();   
    }//GEN-LAST:event_btn_NovoActionPerformed

    private void txt_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pesquisaActionPerformed
        // private void txt_pesquisaKeyReleased(java.awt.event.KeyEvent evt){
    }//GEN-LAST:event_txt_pesquisaActionPerformed

    private void txt_pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisaKeyReleased
        try{
            String pesquisa = " select * from tbldisciplinas where NomeDisc like '" + txt_pesquisa.getText()+"%'";
            con_disciplina.executaSQL(pesquisa);
            if(con_disciplina.resultset.first()){
                preencherTabela();
            }
            else{
                JOptionPane.showMessageDialog(null,"\n Não existe dados com este paramêtro!!","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(SQLException errosql){
            JOptionPane.showMessageDialog(null,"\n Os dados digitados não foram localizados!! :\n "+errosql,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pesquisaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Alterar;
    private javax.swing.JButton btn_Anterior;
    private javax.swing.JButton btn_Gravar;
    private javax.swing.JButton btn_Novo;
    private javax.swing.JButton btn_PrimeiroRegistro;
    private javax.swing.JButton btn_Proximo;
    private javax.swing.JButton btn_Ultimo;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_CodDisc;
    private javax.swing.JLabel lbl_Codigo;
    private javax.swing.JLabel lbl_Descricao;
    private javax.swing.JLabel lbl_Nome;
    private javax.swing.JLabel lbl_pesquisarCliente;
    private javax.swing.JTable tblDisciplinas;
    private javax.swing.JTextField txt_CodDisc;
    private javax.swing.JTextField txt_Codigo;
    private javax.swing.JTextArea txt_Descricao;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_pesquisa;
    // End of variables declaration//GEN-END:variables
}
