/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package controle;
import conexao.Conexao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author dti
 */
public class Frm_Cursos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_Cursos
     */
    Conexao con_cursos;
    public Frm_Cursos() {
       initComponents(); 
       con_cursos = new Conexao(); // inicialização do objeto
        con_cursos.conecta(); // chama o método que conecta
        con_cursos.executaSQL("select * from tblcursos order by CodCurso");
        preencherTabela();
        posicionarRegistro();
        tblCursos.setAutoCreateRowSorter(true);
    }
    
   public void preencherTabela(){
          tblCursos.getColumnModel().getColumn(0).setPreferredWidth(4);
          tblCursos.getColumnModel().getColumn(1).setPreferredWidth(50);
          tblCursos.getColumnModel().getColumn(2).setPreferredWidth(50);
          tblCursos.getColumnModel().getColumn(3).setPreferredWidth(120);
          tblCursos.getColumnModel().getColumn(4).setPreferredWidth(30);
         
        
        DefaultTableModel modelo = (DefaultTableModel) tblCursos.getModel();
        modelo.setNumRows(0);
        
        try {
           con_cursos.resultset.beforeFirst();
            while(con_cursos.resultset.next()){
                modelo.addRow(new Object[]{
                   con_cursos.resultset.getString("CodCurso"),con_cursos.resultset.getString("NomeCurso"),con_cursos.resultset.getString("CargaHCurso"),con_cursos.resultset.getString("DescricaoCurso"), con_cursos.resultset.getString("GradeHCurso")

                });
            }
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null,"\n Erro ao listar dados da tabela!! :\n "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void posicionarRegistro(){
        try {
            con_cursos.resultset.first();
            mostrar_Dados();
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null,"Não foi possível posicionar no primeiro registro:"+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    //método que irá mostrar os dados do registro selecionado nos campos de cadastro
    public void mostrar_Dados(){
        try {
            txt_Codigo.setText(con_cursos.resultset.getString("CodCurso"));
            txt_Nome.setText(con_cursos.resultset.getString("NomeCurso"));
            txt_CargaHoraria.setText(con_cursos.resultset.getString("CargaHCurso"));
            txt_Descricao.setText(con_cursos.resultset.getString("DescricaoCurso"));
            txt_gradH.setText(con_cursos.resultset.getString("GradeHCurso"));
           
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null,"Não localizou dados: "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_pesquisarCliente = new javax.swing.JLabel();
        txt_pesquisa = new javax.swing.JTextField();
        lbl_Codigo = new javax.swing.JLabel();
        txt_Codigo = new javax.swing.JTextField();
        lbl_Nome = new javax.swing.JLabel();
        lbl_CargaHoraria = new javax.swing.JLabel();
        lbl_Descricao = new javax.swing.JLabel();
        btn_Novo = new javax.swing.JButton();
        btn_PrimeiroRegistro = new javax.swing.JButton();
        btn_Gravar = new javax.swing.JButton();
        btn_Anterior = new javax.swing.JButton();
        btn_Alterar = new javax.swing.JButton();
        btn_Proximo = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_Ultimo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Descricao = new javax.swing.JTextArea();
        lbl_gradH = new javax.swing.JLabel();
        txt_Nome = new javax.swing.JTextField();
        txt_CargaHoraria = new javax.swing.JTextField();
        txt_gradH = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cursos");

        jPanel1.setBackground(new java.awt.Color(196, 219, 247));
        jPanel1.setPreferredSize(new java.awt.Dimension(949, 685));

        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 50, 98));
        jLabel3.setText("Cursos");

        lbl_pesquisarCliente.setFont(new java.awt.Font("Eras Demi ITC", 0, 15)); // NOI18N
        lbl_pesquisarCliente.setForeground(new java.awt.Color(2, 50, 98));
        lbl_pesquisarCliente.setText("Pesquisar pelo do  nome do Curso:");

        txt_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pesquisaActionPerformed(evt);
            }
        });
        txt_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pesquisaKeyReleased(evt);
            }
        });

        lbl_Codigo.setFont(new java.awt.Font("Eras Demi ITC", 1, 15)); // NOI18N
        lbl_Codigo.setForeground(new java.awt.Color(2, 50, 98));
        lbl_Codigo.setText("Código:");

        lbl_Nome.setFont(new java.awt.Font("Eras Demi ITC", 1, 15)); // NOI18N
        lbl_Nome.setForeground(new java.awt.Color(2, 50, 98));
        lbl_Nome.setText("Nome:");

        lbl_CargaHoraria.setFont(new java.awt.Font("Eras Demi ITC", 1, 15)); // NOI18N
        lbl_CargaHoraria.setForeground(new java.awt.Color(2, 50, 98));
        lbl_CargaHoraria.setText("Carga Horaria:");

        lbl_Descricao.setFont(new java.awt.Font("Eras Demi ITC", 1, 15)); // NOI18N
        lbl_Descricao.setForeground(new java.awt.Color(2, 50, 98));
        lbl_Descricao.setText("Descrição:");

        btn_Novo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add.png"))); // NOI18N
        btn_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovoActionPerformed(evt);
            }
        });

        btn_PrimeiroRegistro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_PrimeiroRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/resultset_first.png"))); // NOI18N
        btn_PrimeiroRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrimeiroRegistroActionPerformed(evt);
            }
        });

        btn_Gravar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/disk.png"))); // NOI18N
        btn_Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GravarActionPerformed(evt);
            }
        });

        btn_Anterior.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/resultset_previous.png"))); // NOI18N
        btn_Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnteriorActionPerformed(evt);
            }
        });

        btn_Alterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/application_edit.png"))); // NOI18N
        btn_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AlterarActionPerformed(evt);
            }
        });

        btn_Proximo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Proximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/resultset_next.png"))); // NOI18N
        btn_Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProximoActionPerformed(evt);
            }
        });

        btn_excluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/application_delete.png"))); // NOI18N
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_Ultimo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/resultset_last.png"))); // NOI18N
        btn_Ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UltimoActionPerformed(evt);
            }
        });

        tblCursos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Carga Horaria", "Descrição", "Grade Horaria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCursosMouseClicked(evt);
            }
        });
        tblCursos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblCursosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblCursos);

        txt_Descricao.setColumns(20);
        txt_Descricao.setRows(5);
        jScrollPane2.setViewportView(txt_Descricao);

        lbl_gradH.setFont(new java.awt.Font("Eras Demi ITC", 1, 15)); // NOI18N
        lbl_gradH.setForeground(new java.awt.Color(2, 50, 98));
        lbl_gradH.setText("Grade Horaria:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(377, 377, 377)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_PrimeiroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_Anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_Proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_Ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(71, 71, 71)
                                        .addComponent(btn_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_Gravar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_Nome)
                                            .addComponent(lbl_Codigo)
                                            .addComponent(lbl_CargaHoraria)
                                            .addComponent(lbl_Descricao))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(txt_CargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_gradH)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_gradH, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(lbl_pesquisarCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Codigo)
                    .addComponent(txt_Codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Nome, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_CargaHoraria, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_gradH, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gradH, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Descricao)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_Ultimo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Anterior, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_Proximo, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(btn_PrimeiroRegistro, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Novo)
                            .addComponent(btn_Gravar)
                            .addComponent(btn_Alterar)
                            .addComponent(btn_excluir))))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pesquisarCliente)
                    .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoActionPerformed
        txt_Codigo.setText("");
        txt_Nome.setText("");
        txt_CargaHoraria.setText("");
        txt_Descricao.setText("");
        txt_gradH.setText("");
        
        txt_Codigo.requestFocus();        
    }//GEN-LAST:event_btn_NovoActionPerformed

    private void btn_PrimeiroRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrimeiroRegistroActionPerformed
               try {
        con_cursos.resultset.first();
        mostrar_Dados();
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o primeiro registro: "+erro);
        }    
    }//GEN-LAST:event_btn_PrimeiroRegistroActionPerformed

    private void btn_GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GravarActionPerformed
        String Cod= txt_Codigo.getText();
        String Nome = txt_Nome.getText(); 
        String CargaH = txt_CargaHoraria.getText();
        String Descricao =  txt_Descricao.getText();
        String GradH = txt_gradH.getText(); 
        
          
        
        try{
            String insert_sql="insert into tblcursos (CodCurso,NomeCurso,CargaHCurso, DescricaoCurso, GradeHCurso) values ('" + Cod+ "','" + Nome + "','" + CargaH + "','" + Descricao + "','" + GradH + "')";
            con_cursos.statement.executeUpdate(insert_sql);
             JOptionPane.showMessageDialog(null, "Gravação realizada ", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
            
            con_cursos.executaSQL("select * from tblcursos order by CodCurso");
            preencherTabela();
            
           
        }
        
        catch(SQLException errosql){
            JOptionPane.showMessageDialog(null, "\n Erro na gravação: \n"+errosql,"Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
        }        
    }//GEN-LAST:event_btn_GravarActionPerformed

    private void btn_AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnteriorActionPerformed
try {
            //atribuindo o numero do id que está em uso á variavel, funcionando como "linha selecionada"
            int id_selecionado =  con_cursos.resultset.getInt(1);

            //se o Id selecionado for maior que 1, então ele irá selecionar o registro anterior, senão, irá para o primeiro
            if(id_selecionado > 1){
                con_cursos.resultset.previous();
                mostrar_Dados();
            }else{
                con_cursos.resultset.first();
                mostrar_Dados();
            }

        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no registro anterior: "+erro);
        }        
    }//GEN-LAST:event_btn_AnteriorActionPerformed

    private void btn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlterarActionPerformed
        String Cod= txt_Codigo.getText();
        String Nome = txt_Nome.getText(); 
        String CargaH = txt_CargaHoraria.getText();
        String Descricao =  txt_Descricao.getText();
        String GradH = txt_gradH.getText(); 
        
        String sql;
        String msg="";
        
        try{
            if(txt_Codigo.getText().equals("0")){
                sql="insert into tblcursos (NomeCurso,CargaHCurso, DescricaoCurso, GradeHCurso) values ('" + Cod+ "','" + Nome + "','" + CargaH + "','" + Descricao + "','" + GradH + "')";
                msg="Gravação de um novo registro";
            }
            else{
                sql="update tblcursos set NomeCurso='" + Nome + "', CargaHCurso='" + CargaH + "', DescricaoCurso='" + Descricao + "', GradeHCurso='" + GradH +"' where CodCurso= " + txt_Codigo.getText();
                msg="Alteração de registro";
            }
           
            con_cursos.statement.executeUpdate(sql);
                 JOptionPane.showMessageDialog(null, " Gravação realizada com sucesso!!!", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);

            con_cursos.executaSQL("select * from tblcursos order by CodCurso");
            preencherTabela();
        }
        
        catch (SQLException errosql){
            JOptionPane.showMessageDialog(null,"\n Erro na gravação:\n"+errosql,"Mensagem do programa",JOptionPane.INFORMATION_MESSAGE);
        }               
    }//GEN-LAST:event_btn_AlterarActionPerformed

    private void btn_ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProximoActionPerformed
try { 
            //se o registro selecionado não for o último, ele irá passar para o próximo registro
            //senão, ele irá para o primeiro registro
            if( con_cursos.resultset.isLast() == false){
                 con_cursos.resultset.next();
                mostrar_Dados();
            }else{
                con_cursos.resultset.first();
               mostrar_Dados(); 
            }
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no próximo registro: "+erro);
        }         
    }//GEN-LAST:event_btn_ProximoActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
  String sql="";
        try{
            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro: ","Confirmar Exclusção",JOptionPane.YES_NO_OPTION,3);
                 if(resposta==0){
                     sql="delete from tblcursos where CodCurso = "+txt_Codigo.getText();
                        int excluir = con_cursos.statement.executeUpdate(sql);
                        if(excluir==1){
                         JOptionPane.showMessageDialog(null,"Exclusão realizada com sucesso!!","Mensageem do Programa",JOptionPane.INFORMATION_MESSAGE);   
                         con_cursos.executaSQL("select * from tblcursos order by CodCurso");
                         con_cursos.resultset.first();
                         preencherTabela();
                         posicionarRegistro();
                        }
                        else{
                            JOptionPane.showInternalMessageDialog(null," Operação cancelada pelo usuário!!","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
                        }
                }
        }
        catch(SQLException excecao){
            JOptionPane.showMessageDialog(null,"Erro na exclusão: "+excecao,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }        // TODO add your handling code here:String sql="";
       
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_UltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UltimoActionPerformed
try {
            con_cursos.resultset.last();
            mostrar_Dados();
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no último registro: "+erro);
        }              
    }//GEN-LAST:event_btn_UltimoActionPerformed

    private void tblCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCursosMouseClicked
        int linha_selecionada = tblCursos.getSelectedRow();
        txt_Codigo.setText(tblCursos.getValueAt(linha_selecionada,0).toString());
        txt_Nome.setText(tblCursos.getValueAt(linha_selecionada, 1).toString());
        txt_CargaHoraria.setText(tblCursos.getValueAt(linha_selecionada, 2).toString());
        txt_Descricao.setText(tblCursos.getValueAt(linha_selecionada, 3).toString());
        txt_gradH.setText(tblCursos.getValueAt(linha_selecionada, 4).toString()); 
    }//GEN-LAST:event_tblCursosMouseClicked

    private void tblCursosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCursosKeyPressed
        int linha_selecionada = tblCursos.getSelectedRow();
        txt_Codigo.setText(tblCursos.getValueAt(linha_selecionada,0).toString());
        txt_Nome.setText(tblCursos.getValueAt(linha_selecionada, 1).toString());
        txt_CargaHoraria.setText(tblCursos.getValueAt(linha_selecionada, 2).toString());
        txt_Descricao.setText(tblCursos.getValueAt(linha_selecionada, 3).toString());
        txt_gradH.setText(tblCursos.getValueAt(linha_selecionada, 4).toString());       
    }//GEN-LAST:event_tblCursosKeyPressed

    private void txt_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pesquisaActionPerformed
        // private void txt_pesquisaKeyReleased(java.awt.event.KeyEvent evt){
    }//GEN-LAST:event_txt_pesquisaActionPerformed

    private void txt_pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisaKeyReleased
        try{
            String pesquisa = " select * from tblcursos where NomeCurso like '" + txt_pesquisa.getText()+"%'";
            con_cursos.executaSQL(pesquisa);
            if(con_cursos.resultset.first()){
                preencherTabela();
            }
            else{
                JOptionPane.showMessageDialog(null,"\n Não existe dados com este paramêtro!!","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(SQLException errosql){
            JOptionPane.showMessageDialog(null,"\n Os dados digitados não foram localizados!! :\n "+errosql,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }        // TODO add your handling code here:

    }//GEN-LAST:event_txt_pesquisaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Alterar;
    private javax.swing.JButton btn_Anterior;
    private javax.swing.JButton btn_Gravar;
    private javax.swing.JButton btn_Novo;
    private javax.swing.JButton btn_PrimeiroRegistro;
    private javax.swing.JButton btn_Proximo;
    private javax.swing.JButton btn_Ultimo;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_CargaHoraria;
    private javax.swing.JLabel lbl_Codigo;
    private javax.swing.JLabel lbl_Descricao;
    private javax.swing.JLabel lbl_Nome;
    private javax.swing.JLabel lbl_gradH;
    private javax.swing.JLabel lbl_pesquisarCliente;
    private javax.swing.JTable tblCursos;
    private javax.swing.JTextField txt_CargaHoraria;
    private javax.swing.JTextField txt_Codigo;
    private javax.swing.JTextArea txt_Descricao;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_gradH;
    private javax.swing.JTextField txt_pesquisa;
    // End of variables declaration//GEN-END:variables
}
